name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
    
    
    - name: Checkout frontend file
      uses: actions/checkout@v3
      with:
        repository: upssokarthik/static-files
        path: static-files
    
    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AZURE_DOCKER_USER }}
        password: ${{ secrets.AZURE_DOCKER_PASS }}


    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: uperformkarthick/sample-todo-python:dev
        file: Dockerfile
        context: .
